# Generated by Django 4.2.19 on 2025-03-10 18:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0002_article_likes_alter_comment_article"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="favorited_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="favorite_articles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
